### ISSUE TITLE
info.extract() does not get properly the content filename

### ISSUE THREAD

**Issue by dpalic** [axet/wget#10]
on all tested webservers
- virtualBox sample
- sonatype nexus
- apache

The DownloadInfo (UrlInfo) does not extract properly the content file name. It is always null.

**Comment by axet** [comment]
does the server return it?

**Comment by dpalic** [comment]
using also this example from the test cases:
http://download.virtualbox.org/virtualbox/5.0.16/VirtualBox-5.0.16-105871-OSX.dmg
It does also not report the Content-Disposition header.

`      String contentDisposition = conn.getHeaderField("Content-Disposition");`

So if I have got you properly, no the header is not set.
Shouldn't the UrlInfo report the filename in any case?

**Comment by axet** [comment]
Nope. Only if server sends it.

**Comment by dpalic** [comment]
I am not sure what your suggestion about this usage is?
If I compare to wget, as a user I am getting the filename provided independently if the header is set:
http://download.virtualbox.org/virtualbox/5.0.16/VirtualBox-5.0.16-105871-OSX.dmg
it stores the file under VirtualBox-5.0.16-105871-OSX.dmg

So my assumption was that java wget will do the same?

**Comment by axet** [comment]
It does handle it. And had nothing to do with content disposition.

**Comment by dpalic** [comment]
maybe we talk about two different issues.
My assumption was the content-disposition will provide the details, so it is not the fact.

I am also orienting on the examples provided in ExampleApplicationManaged

```
            // Choice target file or set download folder
            File target = new File("/Users/axet/Downloads/VirtualBox-5.0.16-105871-OSX.dmg");
            // create wget downloader
            WGet w = new WGet(info, target);

```

In this case I have to know in advance the filename and to provide it as "target"
The next issue is also I need to store the file - in same name as provided by webserver - in a specific folder.
The filename is either provided by content-disposition or by the URL. So far I have got you properly.

How can I handle both requirements?
I can parse myself from URL the filename if DownloadInfo.contentFilename() is reporting null, but it would be from perspective of usage better if the method would return the filename properly.

**Comment by axet** [comment]
What wrong with letting library choice a file?

```java
File target = new File("/Users/axet/Downloads/");
// create wget downloader
WGet w = new WGet(info, target);
```

**Comment by dpalic** [comment]
sorry I am not getting your point.
The library? You mean the caller/user of your java-wget-library decides the filename in advance?

From the user/developers perspective the usage of the extracted downloadInfo is not straight forward. 
I only report this issue, since it is not fully behaving like wget on cmd line. 
So, since you are the owner of the lib you decide if you want to have the requested improvement or not. I would still suggest to be able to provide a target folder and the filename will be extracted by the DownloadInfo.
If the user/developer wants to set the filename he can easily define it with the existing constructors.

Means to have 
```
Path tmpFolder = Files.createTempDirectory("WGet-");
new WGet(info, tmpFolder.toFile());

```
or by having
`info.getContentFilename() `
to report the content-disposition if not null or the URL basename of the file.

Hope I could clear my point of view now

**Comment by axet** [comment]
WGet class has two constructors:

```
    public WGet(URL source, File target) {
    public WGet(DownloadInfo info, File targetFile) {
```

Use the one you need, seems like the first one.

or use targetFile with:

```
WGet.calcName(info, target)
```

**Comment by dpalic** [comment]
okay giving up, seems I cannot explain the issue.

till now my code:
```
         info = new DownloadInfo(lUrl);
         // extract information from the given URL
         info.extract(stop, lNotify);

         if (info.getRange()) {
            // enable multipart donwload, if range is available
            info.enableMultipart();
         }
         // init speedinfo
         speedInfo.start(0);

         lWget.download(stop, lNotify);

         // end speedinfo
         speedInfo.end(info.getCount());

```

new code 

```
         lTmpPath = Files.createTempDirectory("WGet-");

         // create wget downloader
         WGet lWget = new WGet(url, lTmpPath.toFile());
         DownloadInfo lInfo = lWget.getDownloadInfo();
         // extract information from the given URL
         info.extract(stop, lNotify);

         if (info.getRange()) {
            // enable multipart donwload, if range is available
            info.enableMultipart();
         }

         // init speedinfo
         speedInfo.start(0);

         lWget.download(stop, lNotify);

         // end speedinfo
         speedInfo.end(info.getCount());
```
    
Do I get it correctly, your intention is to have a asymmetric API call dependent on the usage?
