### ISSUE TITLE
Old Commons IO version

### ISSUE THREAD

**Issue by iSach** [axet/wget#12]
Hello,

I'm trying to use get which uses this with JDA. (Discord API for Java)
but the problem is that you're using Commons IO 2.1 and JDA uses 2.4, and I'm having issues because of that.
So I was wondering if you could fix that? 
Thanks in advance!

**Comment by axet** [comment]
Use maven/gradle ignore dependency technique.  I maybe fix it later

**Comment by iSach** [comment]
still doesn't fix problem.
Getting this as error stack trace:
http://pastebin.com/kt3Rj8Nc

**Comment by axet** [comment]
I moved to 2.5 may this a problem
