### ISSUE TITLE
Corrupt File

### ISSUE THREAD

**Issue by mcjp78** [axet/wget#14]
Hello!
I am trying to download a .torrent file with Wget and the file always winds up corrupted. Could you help?
Thanks!

**Comment by axet** [comment]
Explain what are you doing

**Comment by mcjp78** [comment]
I am downloading a direct torrent file from torcache. It works in chrome

Sent from my iPhone

On Jun 19, 2016, at 10:35 PM, Alexey Kuznetsov <notifications@github.com<mailto:notifications@github.com>> wrote:


Explain what are you doing

-

**Comment by axet** [comment]
Why makes you think it is wget library issue?

**Comment by mcjp78** [comment]
Because I have cross tested it against chrome where the file isn't corrupted?

**Comment by axet** [comment]
Have you checked input URL? Does it have redirects? Maybe server block this connection?

**Comment by mcjp78** [comment]
I did infact, no.redirects, nothing.

Sent from my iPhone

On Jun 20, 2016, at 10:13 AM, Alexey Kuznetsov <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you checked input URL? Does it have redirects? Maybe server block this connection?

-

**Comment by axet** [comment]
What corrupt torrent file contains?
