### ISSUE TITLE
Be able to override PART_LENGTH

### ISSUE THREAD

**Issue by CmdrDats** [axet/wget#15]
In DownloadInfo:

https://github.com/axet/wget/blob/4526e9186ac11c3583e76ba405ff48db135561cb/src/main/java/com/github/axet/wget/info/DownloadInfo.java#L189

It calculates the number of parts based on a constant PART_LENGTH, which is should be overridable (perhaps by introducing a parameter and another no-param enableMultipart that takes PART_LENGTH by default)

That way, I could implement the notion of "I want 16 parts, please". Would be nice to also have this in there, but that's easy to implement with the ability to override PART_LENGTH

**Comment by axet** [comment]
Good point. Now you can ovveride global PART_LENGTH param, or use direct enableMultiParts(long) method

**Comment by CmdrDats** [comment]
thanks! :) good idea with adding the getPartLength too :)
