### ISSUE TITLE
It does not work when trying to download files from sourceforge

### ISSUE THREAD

**Issue by nokiajavi** [axet/wget#17]
Hi, I'm trying to use their library to download a file from sourceforge.

I tried it with a windows application that implements WGET, and it works but from downloading java, with your library does not work, it seems that does not perform redirection correctly.

Here I leave the url of the file you want to download:
https://sourceforge.net/projects/actualizadorjlojch/files/2.2/ActualizadorJLOJCH.jar

Grettings

**Comment by axet** [comment]
fixed 1.3.0
