### ISSUE TITLE
cannot resolve symbol 'LimitThreadPool'?

### ISSUE THREAD

**Issue by AlpacaMan233** [axet/wget#23]
When I copy wget into my project and compile, I get the error: cannot resolve symbol 'LimitThreadPool'.
![2](https://cloud.githubusercontent.com/assets/22738837/21560245/f0e7d16c-ce96-11e6-9ca7-64d79f224c95.png)

**Comment by axet** [comment]
You have to use maven

**Comment by AlpacaMan233** [comment]
I'll learn to use maven, but not now. Could you tell where is the `LimitThreadPool` class and why will I get this error?

**Comment by axet** [comment]
then learn how to download maven dependencies using ivy. oh wait, you have to learn maven first.

not possible! see u!

**Comment by AlpacaMan233** [comment]
I just delete anything relative to `LimitThreadPool` and it works fine. IMHO your library and code is too fat.

**Comment by axet** [comment]
My library cover many use cases some of them requires 'LimitThreadPool', I glad it worked well without redundant code!

Happy new year!
