### ISSUE TITLE
Video Youtube of "Vevo" direct link not working!

### ISSUE THREAD

**Issue by trungptdhcn** [axet/wget#5]
I trying use your library to download video from youtube. I have problem with video of "Vevo". I got direct link from youtube but It not working. Please help me reslove this issue Thank, This is link video from vevo:
<i>https://r5---sn-8qj-i5oek.googlevideo.com/videoplayback?lmt=1441448818674033&requiressl=yes&dur=234.707&fexp=9406001%2C9408254%2C9408710%2C9413320%2C9414764%2C9416126%2C9416729%2C9417367%2C9417707%2C9418906%2C9421165%2C9421409%2C9422596%2C9422780%2C9422976%2C9423294%2C9423663&pl=19&itag=22&source=youtube&expire=1446565812&mime=video%2Fmp4&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ratebypass=yes&sver=3&ipbits=0&initcwndbps=3131250&key=yt6&ip=14.160.70.230&ms=au&mt=1446544083&mv=m&id=o-AAbkYb2uZT75Qbso4iuuNGOeqXwY-RJ36T0iiIqbq5OU&mm=31&mn=sn-8qj-i5oek&upn=0uTihk9RUDw&signature=438FA0346DA4AEEE00EA69459E5DEB3D35393C.5D72E03BD7EB7E715DB8E442793A84C7365CC2636E</i>
And this is other video:
<i> https://r7---sn-8qj-i5oek.googlevideo.com/videoplayback?upn=Lo9eD4228QQ&id=o-AJsalJ60Rvf95lE5oczZnhex_GQbfasZrayeSUkosuff&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mn=sn-8qj-i5oek&ms=au&mt=1446545091&mv=m&key=yt6&ip=14.160.70.230&pcm2cms=yes&requiressl=yes&lmt=1394317339461033&mime=video%2Fmp4&fexp=9406714%2C9406993%2C9408710%2C9414764%2C9415436%2C9416126%2C9417345%2C9417656%2C9417707%2C9418400%2C9419545%2C9420312%2C9420440%2C9421211%2C9421947%2C9422299%2C9422596%2C9422910%2C9423429%2C9423663&mm=31&expire=1446566724&source=youtube&dur=485.831&pl=19&itag=22&initcwndbps=2905000&ipbits=0&ratebypass=yes&sver=3&signature=399A35E1153934B8E6A7BE3C2128894ABEC49B7B.35F091891ED2490103FA6AE09206203968728045&signature=399A35E1153934B8E6A7BE3C2128894ABEC49B7B.35F091891ED2490103FA6AE09206203968728045</i>

**Comment by axet** [comment]
wget library has nothing to do with youtube.
