### ISSUE TITLE
Issue with SpeedInfo on very fast downloads

### ISSUE THREAD

**Issue by dpalic** [axet/wget#9]
SpeedInfo has a issue with very fast downloads.
If the download takes less than SAMPLE_LENGTH or the amount of samples is only 1 sample.
The issue is on very fast networks (e.g. 1GBit interfaces) even 10MB (sometimes also 100MB / 800MBit) transfers are reported as 0.0 MBps transfers since the transfers take less than SAMPLE_LENGTH
So the reported values of following are always 0 MBps.
getCurrentSpeed()
getAverageSpeed()
To simulate the behaviour you can provide a small file on IIS or on apache locally and download it locally.

Also I would suggest to rename
Sample#current to Sample#downloadedBytes or something more understandable.

Let me know if I can help you in any case.

**Comment by axet** [comment]
try new

```java
speedInfo.end(info.getCount());
```

**Comment by dpalic** [comment]
thank you for the quick fix! It is working fine
